[package]
name = "crypto_core"
version = "0.1.0"
edition = "2024"

[dependencies]
md5 = { workspace = true }
aes = { workspace = true }
des = { workspace = true }
cbc = { workspace = true }
ecb = { workspace = true }
cipher = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
