[package]
name = "gpui-crittoutil"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gpui-crittoutil"
path = "src/main.rs"

[dependencies]
gpui = { workspace = true }
gpui_platform = { workspace = true }
gpui-component = { workspace = true }
gpui-component-assets = { workspace = true }
anyhow = { workspace = true }

crypto_core = { workspace = true }
converter = { workspace = true }
home = { workspace = true }
session = { workspace = true }
agent = { workspace = true }

rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
